name: Lint

on: push

jobs:
   eslint:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v3
         - name: Install Node.js
           uses: actions/setup-node@v3
           with:
              node-version: 18
         - name: Setup and cache pnpm
           uses: ./.github/actions/pnpm-setup
         - name: Install workspaces
           run: pnpm install
         - name: Run ESLint
           run: pnpm lint
